        [platformio]
        default_envs = disco_f407vg

        [env:disco_f407vg]
        platform = ststm32
        board = disco_f407vg
        framework = stm32cube
        upload_port = COM5
monitor_port = COM5
debug_port = COM5

        [env]

        ; Platform packages
        platform_packages =
            platformio/framework-stm32cubef4@^1.28.3
